const baseUrl = "http://127.0.0.1:8000/api";

export const productsList = [
    {
        id: 1,
        brand: "lenovo",
        quantity: 3,
        name: "laptop",
        price: 123,
        category: "laptop",
        desc: "bla bla bla bla",
        imgUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRLCcgAErhztPkNG9g-hZCMxkKuyaQHq0aTGgJ-RkHTMg&s",
    },
    {
        id: 1,
        brand: "lenovo",
        quantity: 3,
        name: "laptop",
        price: 123,
        category: "laptop",
        desc: "bla bla bla bla",
        imgUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRLCcgAErhztPkNG9g-hZCMxkKuyaQHq0aTGgJ-RkHTMg&s",
    },
    {
        id: 2,
        name: "laptop",
        price: 123,
        quantity: 3,
        brand: "lenovo",
        category: "laptop",
        desc: "bla bla bla bla",
        imgUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRLCcgAErhztPkNG9g-hZCMxkKuyaQHq0aTGgJ-RkHTMg&s",
    },
    {
        id: 7,
        name: "laptop",
        category: "laptop",
        price: 123,
        brand: "lenovo",
        desc: "bla bla bla bla",
        imgUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRLCcgAErhztPkNG9g-hZCMxkKuyaQHq0aTGgJ-RkHTMg&s",
    },
    {
        id: 1,
        brand: "lenovo",
        quantity: 3,
        name: "laptop",
        price: 123,
        category: "laptop",
        desc: "bla bla bla bla",
        imgUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRLCcgAErhztPkNG9g-hZCMxkKuyaQHq0aTGgJ-RkHTMg&s",
    },
    {
        id: 2,
        name: "laptop",
        price: 123,
        quantity: 3,
        brand: "lenovo",
        category: "laptop",
        desc: "bla bla bla bla",
        imgUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRLCcgAErhztPkNG9g-hZCMxkKuyaQHq0aTGgJ-RkHTMg&s",
    },
    {
        id: 7,
        name: "laptop",
        category: "laptop",
        price: 123,
        brand: "lenovo",
        desc: "bla bla bla bla",
        imgUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRLCcgAErhztPkNG9g-hZCMxkKuyaQHq0aTGgJ-RkHTMg&s",
    },
    {
        id: 1,
        brand: "lenovo",
        quantity: 3,
        name: "laptop",
        price: 123,
        category: "laptop",
        desc: "bla bla bla bla",
        imgUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRLCcgAErhztPkNG9g-hZCMxkKuyaQHq0aTGgJ-RkHTMg&s",
    },
    {
        id: 2,
        name: "laptop",
        price: 123,
        quantity: 3,
        brand: "lenovo",
        category: "laptop",
        desc: "bla bla bla bla",
        imgUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRLCcgAErhztPkNG9g-hZCMxkKuyaQHq0aTGgJ-RkHTMg&s",
    },
    {
        id: 7,
        name: "laptop",
        category: "laptop",
        price: 123,
        brand: "lenovo",
        desc: "bla bla bla bla",
        imgUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRLCcgAErhztPkNG9g-hZCMxkKuyaQHq0aTGgJ-RkHTMg&s",
    },
    {
        id: 1,
        brand: "lenovo",
        quantity: 3,
        name: "laptop",
        price: 123,
        category: "laptop",
        desc: "bla bla bla bla",
        imgUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRLCcgAErhztPkNG9g-hZCMxkKuyaQHq0aTGgJ-RkHTMg&s",
    },
    {
        id: 2,
        name: "laptop",
        price: 123,
        quantity: 3,
        brand: "lenovo",
        category: "laptop",
        desc: "bla bla bla bla",
        imgUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRLCcgAErhztPkNG9g-hZCMxkKuyaQHq0aTGgJ-RkHTMg&s",
    },
    {
        id: 7,
        name: "laptop",
        category: "laptop",
        price: 123,
        brand: "lenovo",
        desc: "bla bla bla bla",
        imgUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRLCcgAErhztPkNG9g-hZCMxkKuyaQHq0aTGgJ-RkHTMg&s",
    },
    {
        id: 1,
        brand: "lenovo",
        quantity: 3,
        name: "laptop",
        price: 123,
        category: "laptop",
        desc: "bla bla bla bla",
        imgUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRLCcgAErhztPkNG9g-hZCMxkKuyaQHq0aTGgJ-RkHTMg&s",
    },
    {
        id: 2,
        name: "laptop",
        price: 123,
        quantity: 3,
        brand: "lenovo",
        category: "laptop",
        desc: "bla bla bla bla",
        imgUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRLCcgAErhztPkNG9g-hZCMxkKuyaQHq0aTGgJ-RkHTMg&s",
    },
    {
        id: 2,
        name: "laptop",
        price: 123,
        quantity: 3,
        brand: "lenovo",
        category: "laptop",
        desc: "bla bla bla bla",
        imgUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRLCcgAErhztPkNG9g-hZCMxkKuyaQHq0aTGgJ-RkHTMg&s",
    },
    {
        id: 7,
        name: "laptop",
        category: "laptop",
        price: 123,
        brand: "lenovo",
        desc: "bla bla bla bla",
        imgUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRLCcgAErhztPkNG9g-hZCMxkKuyaQHq0aTGgJ-RkHTMg&s",
    },
    {
        id: 1,
        brand: "lenovo",
        quantity: 3,
        name: "laptop",
        price: 123,
        category: "laptop",
        desc: "bla bla bla bla",
        imgUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRLCcgAErhztPkNG9g-hZCMxkKuyaQHq0aTGgJ-RkHTMg&s",
    },
    {
        id: 2,
        name: "laptop",
        price: 123,
        quantity: 3,
        brand: "lenovo",
        category: "laptop",
        desc: "bla bla bla bla",
        imgUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRLCcgAErhztPkNG9g-hZCMxkKuyaQHq0aTGgJ-RkHTMg&s",
    },
    {
        id: 2,
        name: "laptop",
        price: 123,
        quantity: 3,
        brand: "lenovo",
        category: "laptop",
        desc: "bla bla bla bla",
        imgUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRLCcgAErhztPkNG9g-hZCMxkKuyaQHq0aTGgJ-RkHTMg&s",
    },
    {
        id: 7,
        name: "laptop",
        category: "laptop",
        price: 123,
        brand: "lenovo",
        desc: "bla bla bla bla",
        imgUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRLCcgAErhztPkNG9g-hZCMxkKuyaQHq0aTGgJ-RkHTMg&s",
    },
    {
        id: 1,
        brand: "lenovo",
        quantity: 3,
        name: "laptop",
        price: 123,
        category: "laptop",
        desc: "bla bla bla bla",
        imgUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRLCcgAErhztPkNG9g-hZCMxkKuyaQHq0aTGgJ-RkHTMg&s",
    },
    {
        id: 2,
        name: "laptop",
        price: 123,
        quantity: 3,
        brand: "lenovo",
        category: "laptop",
        desc: "bla bla bla bla",
        imgUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRLCcgAErhztPkNG9g-hZCMxkKuyaQHq0aTGgJ-RkHTMg&s",
    },
    {
        id: 2,
        name: "laptop",
        price: 123,
        quantity: 3,
        brand: "lenovo",
        category: "laptop",
        desc: "bla bla bla bla",
        imgUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRLCcgAErhztPkNG9g-hZCMxkKuyaQHq0aTGgJ-RkHTMg&s",
    },
    {
        id: 7,
        name: "laptop",
        category: "laptop",
        price: 123,
        brand: "lenovo",
        desc: "bla bla bla bla",
        imgUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRLCcgAErhztPkNG9g-hZCMxkKuyaQHq0aTGgJ-RkHTMg&s",
    },
    {
        id: 1,
        brand: "lenovo",
        quantity: 3,
        name: "laptop",
        price: 123,
        category: "laptop",
        desc: "bla bla bla bla",
        imgUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRLCcgAErhztPkNG9g-hZCMxkKuyaQHq0aTGgJ-RkHTMg&s",
    },
    {
        id: 2,
        name: "laptop",
        price: 123,
        quantity: 3,
        brand: "lenovo",
        category: "laptop",
        desc: "bla bla bla bla",
        imgUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRLCcgAErhztPkNG9g-hZCMxkKuyaQHq0aTGgJ-RkHTMg&s",
    },
    {
        id: 7,
        name: "laptop",
        category: "laptop",
        price: 123,
        brand: "lenovo",
        desc: "bla bla bla bla",
        imgUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRLCcgAErhztPkNG9g-hZCMxkKuyaQHq0aTGgJ-RkHTMg&s",
    },
    {
        id: 1,
        brand: "lenovo",
        quantity: 3,
        name: "laptop",
        price: 123,
        category: "laptop",
        desc: "bla bla bla bla",
        imgUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRLCcgAErhztPkNG9g-hZCMxkKuyaQHq0aTGgJ-RkHTMg&s",
    },
    {
        id: 2,
        name: "laptop",
        price: 123,
        quantity: 3,
        brand: "lenovo",
        category: "laptop",
        desc: "bla bla bla bla",
        imgUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRLCcgAErhztPkNG9g-hZCMxkKuyaQHq0aTGgJ-RkHTMg&s",
    },
    {
        id: 7,
        name: "laptop",
        category: "laptop",
        price: 123,
        brand: "lenovo",
        desc: "bla bla bla bla",
        imgUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRLCcgAErhztPkNG9g-hZCMxkKuyaQHq0aTGgJ-RkHTMg&s",
    },
    {
        id: 2,
        name: "laptop",
        price: 123,
        quantity: 3,
        brand: "lenovo",
        category: "laptop",
        desc: "bla bla bla bla",
        imgUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRLCcgAErhztPkNG9g-hZCMxkKuyaQHq0aTGgJ-RkHTMg&s",
    },
    {
        id: 7,
        name: "laptop",
        category: "laptop",
        price: 123,
        brand: "lenovo",
        desc: "bla bla bla bla",
        imgUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRLCcgAErhztPkNG9g-hZCMxkKuyaQHq0aTGgJ-RkHTMg&s",
    },
    {
        id: 3,
        name: "laptop",
        category: "laptop",
        price: 123,
        quantity: 3,
        brand: "lenovo",
        desc: "bla bla bla bla",
        imgUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRLCcgAErhztPkNG9g-hZCMxkKuyaQHq0aTGgJ-RkHTMg&s",
    },
    {
        id: 4,
        name: "laptop",
        price: 123,
        quantity: 3,
        brand: "lenovo",
        brand: "lenovo",
        category: "laptop",
        desc: "bla bla bla bla",
        imgUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRLCcgAErhztPkNG9g-hZCMxkKuyaQHq0aTGgJ-RkHTMg&s",
    },
    {
        id: 5,
        name: "laptop",
        category: "laptop",
        quantity: 3,
        brand: "dell",
        price: 123,
        desc: "ou a web developer? Would you like to collaborate on CSSMatic? Contact us. Designed and developed by.",
        imgUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRLCcgAErhztPkNG9g-hZCMxkKuyaQHq0aTGgJ-RkHTMg&s",
    },
    {
        id: 6,
        name: "laptop",
        price: 123,
        brand: "lenovo",
        quantity: 3,
        category: "laptop",
        desc: "bla bla bla bla",
        imgUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRLCcgAErhztPkNG9g-hZCMxkKuyaQHq0aTGgJ-RkHTMg&s",
    },
];

export const usersList = [
    {
        id: 1,
        firstname: "ali",
        lastname: "samir",
        email: "ali@gmail.com",
        country: "lebanon",
        city: "tripoli",
        purchaseAmount: 1000,
        phoneNumber: "70/012312",
    },
    {
        id: 3,
        firstname: "omar",
        lastname: "tamer",
        email: "ali@gmail.com",
        country: "lebanon",
        city: "tripoli",
        purchaseAmount: 1000,
        phoneNumber: "70/012312",
    },
    {
        id: 2,
        firstname: "sousou",
        lastname: "siso",
        email: "ali@gmail.com",
        country: "lebanon",
        city: "tripoli",
        purchaseAmount: 1000,
        phoneNumber: "70/012312",
    },
];
export default baseUrl;
